version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - github-actions
    commit-message:
      prefix: build
      include: scope
  - package-ecosystem: npm
    directory: /
    schedule:
      interval: daily
      time: '04:00'
      timezone: America/Toronto
    versioning-strategy: increase
    rebase-strategy: auto
    labels:
      - auto
      - dependencies
      - javascript
    commit-message:
      prefix: chore
      include: scope
    groups:
      eslint:
        dependency-type: development
        patterns:
          - eslint
          - '@devpow112/eslint-*'
      commitlint:
        dependency-type: development
        patterns:
          - '@commitlint/*'
          - '@devpow112/commitlint-*'
      semantic-release:
        dependency-type: development
        patterns:
          - semantic-release
          - conventional-changelog-conventionalcommits
          - '@semantic-release/*'
