name: Release
on:
  push:
    branches: main
concurrency: release
permissions:
  contents: read
jobs:
  ci:
    name: CI
    permissions:
      contents: read
      security-events: write
    uses: ./.github/workflows/ci.yml
  cd:
    name: CD
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs:
      - ci
    permissions:
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.7
        with:
          persist-credentials: false
      - name: Set up node
        uses: actions/setup-node@v4.1.0
        with:
          node-version-file: .nvmrc
          cache: npm
      - name: Install packages
        run: npm ci
      - name: Release
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{secrets.RELEASE_TOKEN}}
          NPM_TOKEN: ${{secrets.NPM_TOKEN}}
